#!/bin/sh

build_dir="build"
bin_name="glwr"

configure() {
    if [ ! -d ${build_dir} ]; then
        echo "Configuring...\n"
        cmake -B build

        if [ "$?" != "0" ]; then
            rm -rf build
        fi
    fi
}

build() {
    echo -e "Building...\n"
    cmake --build build
}

run() {
    echo -e "Running...\n"
    ./${build_dir}/${bin_name}
}

configure && build && run
